CREATE TABLE IF NOT EXISTS match
(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  dateTime TIMESTAMP NOT NULL,
  teamRedGoals INT DEFAULT 0 NOT NULL,
  teamBlueGoals INT DEFAULT 0 NOT NUll,
  teamSize int NOT NULL
);
